name: Extract
on: [push, pull_request]

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install project dependencies
        run: yarn install

      - name: Build packages
        run: yarn type-check

      - name: Extract API
        env:
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
        run: yarn extract:tsdoc-to-portable-text
